In [1]:
import pandas as pd

In [3]:
data = [1,2,3,4,5,6]
series = pd.Series(data)

print("Series \n",series)

Series
 0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [5]:
type(series)

pandas.Series

In [ ]:
dict = {'a':1,'b':2,'c':3}

series = pd.Series(dict)
print(series)

# if we have the dict and we make it as series using the pandas then our index becomes the dict keys and values are dict values

a    1
b    2
c    3
dtype: int64

In [7]:
data = [10,20,30]
index = ['a','b','c']

pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [11]:
#DataFrame
df = pd.read_csv("calories.csv")
df.shape

(15000, 2)

In [12]:
df.head()

    User_ID  Calories
0  14733363     231.0
1  14861698      66.0
2  11179863      26.0
3  16180408      71.0
4  17771927      35.0

In [ ]:
df.tail()

        User_ID  Calories
14995  15644082      45.0
14996  17212577      23.0
14997  17271188      75.0
14998  18643037      11.0
14999  11751526      98.0

In [ ]:
df.dtypes

User_ID       int64
Calories    float64
dtype: object

In [16]:
df["User_ID"]

0        14733363
1        14861698
2        11179863
3        16180408
4        17771927
           ...
14995    15644082
14996    17212577
14997    17271188
14998    18643037
14999    11751526
Name: User_ID, Length: 15000, dtype: int64

In [ ]:
df.loc[231.0 ,0]

User_ID     14733363.0
Calories         231.0
Name: 0, dtype: float64

In [20]:
df.loc["User_ID"]

KeyError: 'User_ID'

In [ ]:
df.iloc[0]